version: '3.8'

# 백엔드 개발 환경 구축용 도커 컨테이너들
services:
  # npm install 이 안되어있으면 작동 안함
  node:
    image: node:18.15-alpine
    container_name: node_dev
    depends_on:
      - postgresql
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    command: npm run start:dev

#  실제 배포 환경
#  node_prod:
#    build: node:18-alpine
#    container_name: node_dev
#    depends_on:
#      - postgresql
#    ports:
#      - "3000:3000"
#    networks:
#      - backend

  postgresql:
    image: postgres:15-alpine
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - type: bind
        source: ./docker-volume/postgres-data
        target: /var/lib/postgresql/data

  redis:
    image: bitnami/redis
    container_name: redis_dev
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - type: bind
        source: ./docker-volume/redis-data
        target: /bitnami
    env_file:
      - .env.dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - backend
    ports:
      - "5050:80"
    volumes:
      - ./docker-volume/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pong@42seoul.kr
      - PGADMIN_DEFAULT_PASSWORD=pong

networks:
  backend:
    driver: bridge