export const MAP_WIDTH = 50;
export const MAP_HEIGHT = 25;
export const PADDLE_OFFSET = 7;
export const MATCH_SCORE = 10;
export const BALL_SPEED = 10;//sqrt(m/s^2);
export const SKILL_DURATION_TIME = 5000;//ms
export const PADDLE_WIDTH = 1;
export const PADDLE_HEIGHT = 5;
export const PADDLE_SPEED = 0.1;
export const BALL_MAX_ANGLE = 0.785398 / 2; //45degree / 2
export const BALL_PI = 3.14159; //180degree